### ISSUE TITLE
Crystal 0.24.1 can't be installed because not in install --list

### ISSUE THREAD

**Issue by endorama** [pine/crystal-build#64]
Crystal version `0.24.1` was not available in `crenv install --list`, as reported by me [here](https://github.com/pine/crystal-build/issues/62#issuecomment-359175448).

@pine added it to the list.

But unfortunately is still not working, I can see it in the list, but trying to install it gives a "Version not found" error.

```
$ crenv install --list
...
0.23.0
0.23.1
0.24.0
0.24.1
0.24.1
$ crenv install 0.24.1
Resolving Crystal download URL by Remote Cache ... ng
Resolving Crystal download URL by GitHub ... ng
Error: Version not found
```
I also see it 2 times in the list.

**Comment by pine** [comment]
@endorama Oh, sorry. I'll check it.

**Comment by pine** [comment]
@endorama I've updated version list. Could you retry install ?

**Comment by endorama** [comment]
@pine everything works now, awesome! Thanks!
